// src/view/components/About.tsx
import React, { useContext } from 'react';
import { AboutActionType } from '../contexts/About';
import { Anchor } from './Anchor';
import { Colors } from '../style-constants/Colors';
import { Context } from '../contexts/Context';
import { Icons } from '../icons/Icons';
import styled from 'styled-components';

// == styles =======================================================================================
const LogoAndVersion = styled.div`
  margin-bottom: 0.2rem;
`;

const Logo = styled.img`
  fill: ${ Colors.fore };
  width: 15rem;
`;

const Version = styled.span`
  margin-left: 0.75rem;
`;

const Description = styled.div`
  margin-bottom: 0.5rem;
`;

const Hr = styled.div`
  margin-bottom: 0.5rem;
  height: 0.0625rem;
  background: ${ Colors.fore };
`;

const LargeA = styled( Icons.AutomatonA )`
  position: absolute;
  right: -0.5rem;
  bottom: -0.5rem;
  width: 11rem;
  fill: ${ Colors.black };
  opacity: 0.2;
`;

const Close = styled( Icons.Close )`
  position: absolute;
  right: 0.4rem;
  top: 0.4rem;
  width: 0.8rem;
  fill: ${ Colors.fore };
  cursor: pointer;

  &:hover {
    opacity: 0.7;
  }
`;

const SubRoot = styled.div`
  position: relative;
  width: calc( 100% - 2rem );
  padding: 0.75rem 1rem;

  a {
    color: ${ Colors.accent };
    text-decoration: none;

    &:hover {
      color: ${ Colors.accentdark };
    }
  }
`;

const Root = styled.div`
  overflow: hidden;
  border-radius: 0.5rem;
  background: ${ Colors.back3 };
  filter: drop-shadow( 0 0 2px ${ Colors.black } );
  font-size: 0.8rem;
`;

// == element ======================================================================================
export interface AboutProps {
  className?: string;
}

export const About = ( { className }: AboutProps ): JSX.Element => {
  const context = useContext( Context.Store );

  return <Root className={ className }>
    <LargeA />
    <SubRoot>
      <LogoAndVersion>
        <Logo as={ Icons.Automaton } />
        <Version>{
          context.state.automaton.instance && context.state.automaton.instance.version
        }</Version>
      </LogoAndVersion>
      <Description>Animation engine for creative coding</Description>
      <Hr />
      Author: <Anchor href="https://github.com/FMS-Cat">FMS_Cat</Anchor><br />
      Repository: <Anchor href="https://github.com/FMS-Cat/automaton/">https://github.com/fms-cat/automaton/</Anchor><br />
      Automaton is distributed under permissive <Anchor href="https://opensource.org/licenses/MIT">MIT License</Anchor><br />
      Shoutouts to <Anchor href="https://www.image-line.com/flstudio/">Image Line Software</Anchor> &lt;3
    </SubRoot>
    <Close onClick={
      () => context.dispatch( { type: AboutActionType.Close } )
    } />
  </Root>;
};

// src/vue/about.vue
<template>
<div>
  <div class="blur-layer"
    @mousedown="blur"
  />
  <div class="root">
    <img class="logo-bg"
      :src="require( '../images/automaton-a.svg' )"
    />

    <img class="close"
      :src="require( '../images/about-close.svg' )"
      @mousedown="blur"
    />

    <div class="content">
      <img class="logo"
        :src="require( '../images/automaton.svg' )"
      />
      <div class="version">{{ automaton.version }}</div><br />
      Animation engine with Timeline GUI for creative coding

      <div class="logo-hr"></div>
      
      Author: <a href="https://github.com/fms-cat/" target="_blank">@FMS_Cat</a><br />
      Repository: <a href="https://github.com/fms-cat/automaton/" target="_blank">https://github.com/fms-cat/automaton/</a><br />
      Automaton is distributed under permissive <a href="https://opensource.org/licenses/MIT" target="_blank">MIT License</a>.<br />
      Shoutouts to <a href="https://www.image-line.com/flstudio/" target="_blank">Image Line Software</a> &lt;3
    </div>
  </div>
</div>
</template>


<script>
export default {
  name: 'about',

  props: [ 'automaton' ],

  data() {
    return {}
  },

  methods: {
    blur() {
      this.$emit( 'blur' );
    }
  }
}
</script>

<style lang="scss" scoped>
@import "./colors.scss";

.blur-layer {
  position: absolute;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;

  background: #00000066;
}

.root {
  position: absolute;
  left: calc( 50% - 17em );
  top: 1em;
  width: 30em;
  padding: 1em;
  overflow: hidden;

  background: $color-back3;
  border-radius: 0.5em;
  color: $color-fore;
  font-size: 0.8em;
  line-height: 1.2;

  filter: drop-shadow( 0 0 2px #000000 );

  a {
    color: $color-accent;
    text-decoration: none;

    &:hover { opacity: 0.7; }
  }

  .logo-bg {
    position: absolute;
    right: -1em;
    bottom: -1em;
    width: 14em;

    opacity: 0.07;
  }

  .content {
    position: relative;

    .logo {
      width: 20em;
      margin-bottom: 0.3em;
    }

    .version {
      display: inline-block;
      vertical-align: bottom;
      margin-left: 4px;
      margin-bottom: 0.3em;
    }

    .logo-hr {
      width: 100%;
      height: 1px;
      margin: 0.5em 0;

      background: $color-foresub;
    }
  }

  .close {
    position: absolute;
    right: 0.5em;
    top: 0.5em;
    width: 1em;

    cursor: pointer;

    &:hover { opacity: 0.7; }
  }
}
</style>
