// packages/automaton-with-gui/src/view/components/ContextMenu.tsx
import { Colors } from '../constants/Colors';
import { ContextMenuEntry } from './ContextMenuEntry';
import { ContextMenuHr } from './ContextMenuHr';
import { useDispatch, useSelector } from '../states/store';
import React, { useCallback, useMemo } from 'react';
import styled from 'styled-components';

// == styles =======================================================================================
const Container = styled.div`
  position: absolute;
  overflow: hidden;
  padding: 0.25rem;
  border-radius: 0.25rem;
  background: ${ Colors.back2 };
  filter: drop-shadow( 0 0 2px ${ Colors.black } );
  font-size: 0.8rem;
`;

const OverlayBG = styled.div`
  position: absolute;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  background: rgba( 0, 0, 0, 0 );
`;

const Root = styled.div`
  position: fixed;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  background: rgba( 0, 0, 0, 0 );
`;

// == element ======================================================================================
export interface ContextMenuProps {
  className?: string;
}

const ContextMenu = ( { className }: ContextMenuProps ): JSX.Element => {
  const dispatch = useDispatch();

  const { position, commands } = useSelector( ( state ) => ( {
    position: state.contextMenu.position,
    commands: state.contextMenu.commands
  } ) );

  const style: React.CSSProperties = useMemo(
    () => {
      const width = document.documentElement.clientWidth;
      const height = document.documentElement.clientHeight;

      const ret: React.CSSProperties = {};
      ( position.x < width - 240 )
        ? ( ret.left = position.x )
        : ( ret.right = width - position.x );
      ( position.y < height - 120 )
        ? ( ret.top = position.y )
        : ( ret.bottom = height - position.y );
      return ret;
    },
    [ position ]
  );

  const handleClickBG = useCallback(
    () => {
      dispatch( { type: 'ContextMenu/Close' } );
    },
    [ dispatch ]
  );

  const handleContextMenuBG = useCallback(
    () => {
      dispatch( { type: 'ContextMenu/Close' } );
    },
    [ dispatch ]
  );

  return <Root
    className={ className }
  >
    <OverlayBG
      onClick={ handleClickBG }
      onContextMenu={ handleContextMenuBG }
    />
    <Container
      style={ style }
    >
      { commands.map( ( command, iCommand ) => (
        command === 'hr'
          ? <ContextMenuHr key={ iCommand } />
          : (
            <ContextMenuEntry
              key={ iCommand }
              name={ command.name }
              description={ command.description }
              onClick={ () => {
                command.callback();
                dispatch( { type: 'ContextMenu/Close' } );
              } }
            />
          )
      ) ) }
    </Container>
  </Root>;
};

export { ContextMenu };

// src/vue/context-menu.vue
<template>
<div>
  <div class="blur-layer"
    v-if="active"
    @mousedown="blur"
  />
  <div class="root"
    v-if="active"
    :style="{
      left: typeof left === 'number' ? `${ left }px` : undefined,
      right: typeof right === 'number' ? `${ right }px` : undefined,
      top: typeof top === 'number' ? `${ top }px` : undefined,
      bottom: typeof bottom === 'number' ? `${ bottom }px` : undefined
    }"
  >
    <div class="command"
      v-for="( command, index ) in commands"
      :key="'command'+index"
      @mouseup="selectCommand( index )"
    >{{ command.text }}</div>
  </div>
</div>
</template>

<script>
export default {
  name: 'context-menu',

  props: [
    'active',
    'x',
    'y',
    'commands'
  ],

  data() {
    return {
      left: 0,
      right: 0,
      top: 0,
      bottom: 0
    };
  },

  methods: {
    blur() {
      this.$emit( 'blur' );
    },

    moveRoot() {
      const x = this.x;
      const y = this.y;
      const w = document.documentElement.clientWidth;
      const h = document.documentElement.clientHeight;

      const bLeftSide = w - 240 < x;
      const bUpSide = h - 40 < y;

      this.left = bLeftSide ? null : x;
      this.right = bLeftSide ? ( w - x ) : null;
      this.top = bUpSide ? null : y;
      this.bottom = bUpSide ? ( h - y ) : null;
    },

    selectCommand( index ) {
      this.commands[ index ].func();
      this.$emit( 'blur' );
    }
  },

  watch: {
    x() { this.moveRoot() },
    y() { this.moveRoot() }
  }
};
</script>

<style lang="scss" scoped>
@import "./colors.scss";

.blur-layer {
  position: fixed;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
}

.root {
  position: fixed;
  white-space: nowrap;
  padding: 0.4em;
  font-size: 0.8em;

  background: rgba( 0, 0, 0, 0.5 );
  border: solid 1px $color-back4;
  color: $color-foresub;
  border-radius: 0.2em;

  filter: drop-shadow( 0 0 2px #000000 );

  .command {
    padding-left: 0.2em;
    padding-right: 2em;

    border-radius: 0.2em;

    cursor: pointer;

    &:hover {
      background: $color-back4;
      color: $color-fore;
    }
  }
}
</style>
