// src/view/components/Header.tsx
import React, { useCallback, useMemo, useState } from 'react';
import { useDispatch, useSelector } from '../states/store';
import { Colors } from '../constants/Colors';
import { HeaderSeekbar } from './HeaderSeekbar';
import { Icons } from '../icons/Icons';
import { Metrics } from '../constants/Metrics';
import styled from 'styled-components';
import { writeClipboard } from '../utils/clipboard';

// == styles =======================================================================================
const StyledHeaderSeekbar = styled( HeaderSeekbar )`
  width: 8rem;
  height: calc( ${ Metrics.headerHeight } - 0.25rem );
`;

const Section = styled.div`
  display: flex;

  & > * {
    margin: 0 0.25rem;
  }
`;

const Button = styled.img<{ disabled?: boolean; active?: boolean }>`
  width: calc( ${ Metrics.headerHeight } - 0.25rem );
  height: calc( ${ Metrics.headerHeight } - 0.25rem );
  fill: ${ ( { disabled: disabled, active: active } ) => disabled ? Colors.gray : active ? Colors.accent : Colors.fore };
  cursor: pointer;

  &:hover {
    fill: ${ ( { disabled: disabled, active: active } ) => disabled ? Colors.gray : active ? Colors.accentdark : Colors.foresub };
  }
`;

const Logo = styled.img`
  height: calc( ( ${ Metrics.headerHeight } - 0.25rem ) * 0.6 );
  margin: calc( ( ${ Metrics.headerHeight } - 0.25rem ) * 0.2 );
  fill: ${ Colors.fore };
  opacity: 0.5;
  cursor: pointer;

  &:hover {
    opacity: 0.8;
  }

  &:active {
    opacity: 0.5;
  }
`;

const Root = styled.div`
  display: flex;
  justify-content: space-between;
  padding: 0.125rem;
  background: ${ Colors.back4 };
`;

// == element ======================================================================================
export interface HeaderProps {
  className?: string;
}

const Header = ( { className }: HeaderProps ): JSX.Element => {
  const dispatch = useDispatch();
  const [ cantUndoThis, setCantUndoThis ] = useState( 0 );
  const [ isSavedRecently, setIsSavedRecently ] = useState( false );
  const {
    automaton,
    isPlaying,
    settingsMode,
    historyIndex,
    historyEntries
  } = useSelector( ( state ) => ( {
    automaton: state.automaton.instance,
    isPlaying: state.automaton.isPlaying,
    settingsMode: state.settings.mode,
    historyIndex: state.history.index,
    historyEntries: state.history.entries
  } ) );

  const handlePlay = useCallback(
    (): void => {
      if ( !automaton ) { return; }
      automaton.togglePlay();
    },
    [ automaton ]
  );

  const handleUndo = useCallback(
    (): void => {
      if ( historyIndex !== 0 ) {
        historyEntries[ historyIndex - 1 ].undo();
        dispatch( { type: 'History/Undo' } );
      } else {
        if ( cantUndoThis === 9 ) {
          window.open( 'https://youtu.be/bzY7J0Xle08', '_blank' );
          setCantUndoThis( 0 );
        } else {
          setCantUndoThis( cantUndoThis + 1 );
        }
      }
    },
    [ historyIndex, historyEntries, cantUndoThis ]
  );

  const handleRedo = useCallback(
    (): void => {
      if ( historyIndex !== historyEntries.length ) {
        historyEntries[ historyIndex ].redo();
        dispatch( { type: 'History/Redo' } );
      }
      setCantUndoThis( 0 );
    },
    [ historyIndex, historyEntries ]
  );

  const undoText = useMemo(
    () => (
      historyIndex !== 0
        ? 'Undo: ' + historyEntries[ historyIndex - 1 ].description
        : 'Can\'t Undo'
    ),
    [ historyIndex, historyEntries ]
  );

  const redoText = useMemo(
    () => (
      historyIndex !== historyEntries.length
        ? 'Redo: ' + historyEntries[ historyIndex ].description
        : 'Can\'t Redo'
    ),
    [ historyIndex, historyEntries ]
  );

  return (
    <Root className={ className }>
      <Section>
        <Button
          as={ isPlaying ? Icons.Pause : Icons.Play }
          active={ 1 as any as boolean } // fuck
          onClick={ handlePlay }
          data-stalker="Play / Pause"
        />
        <StyledHeaderSeekbar />
      </Section>
      <Logo as={ Icons.Automaton }
        onClick={ () => dispatch( { type: 'About/Open' } ) }
        data-stalker={ `Automaton v${ process.env.VERSION! }` }
      />
      <Section>
        <Button
          as={ Icons.Undo }
          onClick={ handleUndo }
          disabled={ historyIndex === 0 }
          data-stalker={ undoText }
        />
        <Button
          as={ Icons.Redo }
          onClick={ handleRedo }
          disabled={ historyIndex === historyEntries.length }
          data-stalker={ redoText }
        />
        <Button
          as={ Icons.Snap }
          onClick={ () => {
            dispatch( {
              type: 'Settings/ChangeMode',
              mode: settingsMode === 'snapping' ? 'none' : 'snapping'
            } );
          } }
          active={ ( settingsMode === 'snapping' ? 1 : 0 ) as any as boolean } // fuck
          data-stalker="Snapping"
        />
        <Button
          as={ Icons.Cog }
          onClick={ () => {
            dispatch( {
              type: 'Settings/ChangeMode',
              mode: settingsMode === 'general' ? 'none' : 'general'
            } );
          } }
          active={ ( settingsMode === 'general' ? 1 : 0 ) as any as boolean } // fuck
          data-stalker="General Settings"
        />
        <Button as={ Icons.Save }
          onClick={ () => {
            const data = automaton!.serialize();
            writeClipboard( JSON.stringify( data ) );
            setIsSavedRecently( true );
            setTimeout( () => {
              setIsSavedRecently( false );
            }, 3000 );
          } }
          data-stalker={ isSavedRecently ? 'Copied!' : 'Copy current status as JSON' }
        />
      </Section>
    </Root>
  );
};

export { Header };

// src/vue/header.vue
<template>
<div>
  <div class="root">
    <div class="row row-center">
      <div class="logobox"
        @click.stop="$emit( 'logoClicked' )"
      >
        <img class="logo"
          :src="require( '../images/automaton.svg' )"
        />
        <div class="version">{{ automaton.version }}</div>
      </div>
    </div>
    <div class="row row-left">
      <img class="button"
        :src="automaton.isPlaying ? require( '../images/pause.svg' ) : require( '../images/play.svg' )"
        :stalker-text="automaton.isPlaying ? 'Pause' : 'Play'"
        @click.stop="automaton.togglePlay()"
      />
      <div class="time"
        @mousedown.stop="seek"
      >
        <div class="current">
          {{ automaton.time.toFixed( 3 ) }}
        </div>
        <div class="length">
          / {{ automaton.length.toFixed( 3 ) }}
        </div>
        <div class="bar bar-bg"
          :style="{ width: '100%' }"
        ></div>
        <div class="bar bar-fg"
          :style="{ width: `${ automaton.progress * 100 }%` }"
        ></div>
      </div>
    </div>
    <div class="row row-right">
      <img class="button"
        :src="require( '../images/undo.svg' )"
        :stalker-text="automaton.getUndoDesc() ? `Undo: ${automaton.getUndoDesc()}` : 'Can\'t undo'"
        @click.stop="undo()"
      />
      <img class="button"
        :src="require( '../images/redo.svg' )"
        :stalker-text="automaton.getRedoDesc() ? `Redo: ${automaton.getRedoDesc()}` : 'Can\'t redo'"
        @click.stop="redo()"
      />
      <img class="button"
        :src="require( '../images/snap.svg' )"
        stalker-text="Snap Settings"
        @click.stop="$emit( 'configSelected', 'snap' )"
      />
      <img class="button"
        :src="require( '../images/cog.svg' )"
        stalker-text="General Config"
        @click.stop="$emit( 'configSelected', 'general' )"
      />
      <img class="button"
        :src="require( '../images/save.svg' )"
        :stalker-text="saveText"
        @click.stop="save"
      />
    </div>
  </div>
</div>
</template>


<script>
export default {
  mounted() {},

  beforeDestroy() {},

  props: [ "automaton" ],

  data() {
    return {
      saveText: 'Copy current state as JSON',
      cantUndoThis: 0
    }
  },

  methods: {
    seek( event ) {
      const width = event.target.offsetWidth;
      const xOffset0 = event.offsetX;
      const xClient0 = event.clientX;

      const isPlaying0 = this.automaton.isPlaying;

      if ( isPlaying0 ) {
        this.automaton.pause();
        this.automaton.seek( this.automaton.length * xOffset0 / width );
      }

      const move = ( event ) => {
        const x = xOffset0 + event.clientX - xClient0;
        this.automaton.seek( this.automaton.length * x / width );
      };

      const up = ( event ) => {
        if ( isPlaying0 ) {
          this.automaton.play();

          window.removeEventListener( 'mousemove', move );
          window.removeEventListener( 'mouseup', up );
        }
      };

      window.addEventListener( 'mousemove', move );
      window.addEventListener( 'mouseup', up );
    },

    undo() {
      if ( this.automaton.getUndoDesc() ) {
        this.automaton.undo();
        this.cantUndoThis = 0;
      } else {
        this.cantUndoThis ++;
        if ( 10 === this.cantUndoThis ) {
          window.open( 'https://youtu.be/bzY7J0Xle08', '_blank' );
          this.cantUndoThis = 0;
        }
      }

      this.$emit( 'historyMoved' );
    },

    redo() {
      this.automaton.redo();

      this.$emit( 'historyMoved' );
    },

    save() {
      const el = document.createElement( 'textarea' );
      el.value = this.automaton.save();
      document.body.appendChild( el );
      el.select();
      document.execCommand( 'copy' );
      document.body.removeChild( el );

      this.saveText = 'Copied!';
      setTimeout( () => {
        this.saveText = 'Copy current state as JSON';
      }, 3000 );
    }
  }
}
</script>

<style lang="scss" scoped>
@import "./colors.scss";

.root {
  position: absolute;
  left: 0;
  top: 0;
  width: calc( 100% - 6px );
  height: calc( 100% - 6px );
  padding: 3px;

  background: $color-back4;

  .row {
    position: absolute;
    top: 3px;
    height: calc( 100% - 6px );
    font-size: 0;

    &.row-left { left: 3px; }
    &.row-right { right: 3px; }
    &.row-center {
      width: 100%;
      text-align: center;
    }

    * {
      margin: 0 3px;
    }

    .logobox {
      display: inline-block;
      vertical-align: bottom;
      position: relative;
      height: 16px;
      padding: 4px 0;
      color: $color-fore;
      opacity: 0.5;

      cursor: pointer;

      &:hover { opacity: 0.8; }

      .logo {
        height: 100%;
      }

      .version {
        display: inline-block;
        margin-left: 4px;
        font-size: 10px;
      }
    }

    .button {
      width: 24px;
      height: 24px;
      margin: 0 3px;

      cursor: pointer;

      &:hover { opacity: 0.7; }
    }

    .time {
      display: inline-block;
      position: relative;
      bottom: 5%;
      vertical-align: bottom;
      width: 100px;
      height: 90%;

      text-align: right;

      cursor: pointer;

      * {
        pointer-events: none;
      }

      .current {
        display: inline-block;
        position: relative;
        font-size: 14px;

        color: $color-fore;

      }

      .length {
        display: inline-block;
        position: relative;
        font-size: 10px;
        margin-left: 0;

        color: $color-foresub;
      }

      .bar {
        display: block;
        position: absolute;
        bottom: 2px;
        left: 0px;
        height: 2px;
        margin: 0;

        &.bar-bg { background: $color-black; }
        &.bar-fg { background: $color-accent; }
      }
    }
  }
}
</style>
