// src/view/components/Scrollable.tsx
import React, { useEffect, useRef, useState } from 'react';
import { Colors } from '../constants/Colors';
import styled from 'styled-components';
import { useDeltaTime, useAnimationFrame } from '../utils/useAnimationFrame';

// == styles =======================================================================================
export const Bar = styled.div`
  position: absolute;
  width: 0.25rem;
  background: ${ Colors.accent };
  border-radius: 0.125rem;
`;

export const Container = styled.div`
  position: absolute;
  width: 100%;
`;

export const Root = styled.div`
  position: relative;
  overflow: hidden;
`;

// == components ===================================================================================
export interface ScrollableProps {
  className?: string;
  children?: JSX.Element[];
  barPosition?: 'left' | 'right';
}

export const Scrollable = ( props: ScrollableProps ): JSX.Element => {
  const { className, children, barPosition } = props;
  const refOpacity = useRef<number>( 0 );
  const [ top, setTop ] = useState<number>( 0 );
  const refRoot = useRef<HTMLDivElement>( null );
  const refContainer = useRef<HTMLDivElement>( null );

  const visibleHeight = refRoot.current?.clientHeight || 0.0;
  const contentHeight = refContainer.current?.clientHeight || 1.0;
  const barHeight = visibleHeight / contentHeight;
  const barTop = top / contentHeight;

  const handleWheel = ( event: WheelEvent ): void => {
    event.preventDefault();
    event.stopPropagation();

    const scrollMax = contentHeight - visibleHeight;
    setTop( Math.min( Math.max( top - event.deltaY, -scrollMax ), 0.0 ) );
    refOpacity.current = 1.0;
  };

  useAnimationFrame( ( delta ) => {
    refOpacity.current *= Math.exp( -5.0 * delta );
  } );

  useEffect( // 🔥 fuck
    () => {
      const root = refRoot.current;
      if ( !root ) { return; }

      root.addEventListener( 'wheel', handleWheel, { passive: false } );
      return () => (
        root.removeEventListener( 'wheel', handleWheel )
      );
    },
    [ handleWheel ]
  );

  return (
    <Root
      ref={ refRoot }
      className={ className }
    >
      <Container
        ref={ refContainer }
        style={ {
          top: `${ top }px`
        } }
      >
        { children }
      </Container>
      <Bar
        style={ {
          height: `${ 100.0 * barHeight }%`,
          top: `${ -100.0 * barTop }%`,
          left: barPosition === 'left' ? 0 : undefined,
          right: barPosition !== 'left' ? 0 : undefined,
          opacity: refOpacity.current
        } }
      />
    </Root>
  );
};

// src/vue/scrollable.vue
<template>
<div class="root" ref="root">
  <div class="inside" ref="inside"
    :style="{ top: top + 'px' }"
    @wheel="onWheel"
  >
    <slot />
  </div>
  <div class="bar"
    :style="{
      top: barTop + '%',
      height: barHeight + '%',
      left: bar === 'left' ? 0 : undefined,
      right: bar === 'right' ? 0 : undefined,
      opacity: barOpacity
    }"
  />
</div>
</template>

<script>
export default {
  props: [
    'bar'
  ],

  data() {
    return {
      top: 0,
      barOpacity: 0.0
    }
  },

  methods: {
    onWheel( event ) {
      event.preventDefault();

      this.top = this.top - event.deltaY;

      const scrollMax = this.$refs.inside.clientHeight - this.$refs.root.clientHeight;
      if ( this.top < -scrollMax ) {
        const overrun = -scrollMax - this.top;
        this.top = -scrollMax;
      }

      if ( 0 < this.top ) {
        const overrun = this.top;
        this.top = 0;
      }

      this.barHeight = 100.0 * this.$refs.root.clientHeight / this.$refs.inside.clientHeight;
      this.barTop = -100.0 * this.top / this.$refs.inside.clientHeight;
      this.barOpacity += Math.min( this.barOpacity + 0.1 * Math.abs( event.deltaY ), 1.0 );
    },

    update() {
      this.barOpacity *= 0.9;
    }
  },

  mounted() {
    const update = () => {
      this.update();
      requestAnimationFrame( update );
    }
    update();
  }
}
</script>

<style lang="scss" scoped>
@import "./colors.scss";

.root {
  position: relative;
  width: 100%;
  overflow: hidden;

  .inside {
    position: absolute;
    left: 0;
    width: 100%;
  }

  .bar {
    position: absolute;
    width: 4px;

    background: $color-accent;
    border-radius: 2px;
  }
}
</style>
