// src/vue/stalker.vue
<template>
<div>
  <div class="root"
    v-if="text"
    :style="{
      left: typeof left === 'number' ? `${ left }px` : undefined,
      right: typeof right === 'number' ? `${ right }px` : undefined,
      top: typeof top === 'number' ? `${ top }px` : undefined,
      bottom: typeof bottom === 'number' ? `${ bottom }px` : undefined
    }"
  >
    {{ text }}
  </div>
</div>
</template>

<script>
export default {
  name: 'stalker',

  data() {
    return {
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      text: ''
    };
  },

  methods: {
    applyStalkerText( el ) {
      setTimeout( () => {
        this.text = el.getAttribute( 'stalker-text' );
      }, 10 ); // 🔥🔥🔥🔥🔥🔥
    }
  },

  mounted() {
    window.addEventListener( 'mousemove', ( event ) => {
      const x = event.clientX;
      const y = event.clientY;
      const w = document.documentElement.clientWidth;
      const h = document.documentElement.clientHeight;

      const bLeftSide = w - 240 < x;
      const bUpSide = h - 40 < y;

      this.left = bLeftSide ? null : x;
      this.right = bLeftSide ? ( w - x ) : null;
      this.top = bUpSide ? null : y;
      this.bottom = bUpSide ? ( h - y ) : null;

      this.applyStalkerText( event.target );
    } );

    window.addEventListener( 'mousedown', ( event ) => {
      this.applyStalkerText( event.target );
    } );

    window.addEventListener( 'mouseup', ( event ) => {
      this.applyStalkerText( event.target );
    } );
  },
};
</script>

<style lang="scss" scoped>
@import "./colors.scss";

.root {
  position: fixed;
  pointer-events: none;
  white-space: nowrap;
  padding: 0.2em 0.4em;
  margin: 10px;
  font-size: 0.8em;

  background: rgba( 0, 0, 0, 0.5 );
  color: $color-fore;
  border-radius: 0.2em;
}
</style>

// src/view/components/Stalker.tsx
import React, { useEffect, useMemo, useState } from 'react';
import { Colors } from '../constants/Colors';
import styled from 'styled-components';

// == styles =======================================================================================
const Root = styled.div`
  position: fixed;
  font-size: 0.75rem;
  padding: 0.125rem 0.25rem;
  margin: 0.5rem 1rem;
  background: ${ Colors.back1 };
  border-radius: 0.25rem;
  opacity: 0.8;
`;

// == element ======================================================================================
export interface StalkerProps {
  className?: string;
}

const Stalker = ( { className }: StalkerProps ): JSX.Element => {
  const [ position, setPosition ] = useState( { x: 0, y: 0 } );
  const [ target, setTarget ] = useState<EventTarget | null>( null );

  useEffect( // add event listener
    () => {
      function handleMouseMove( event: MouseEvent ): void {
        setPosition( { x: event.clientX, y: event.clientY } );
        setTarget( event.target );
      }

      window.addEventListener( 'mousemove', handleMouseMove );
      return () => window.removeEventListener( 'mousemove', handleMouseMove );
    },
    []
  );

  const style: React.CSSProperties = useMemo(
    () => {
      const width = document.documentElement.clientWidth;
      const height = document.documentElement.clientHeight;

      const ret: React.CSSProperties = {};
      ( position.x < width - 240 )
        ? ( ret.left = position.x )
        : ( ret.right = width - position.x );
      ( position.y < height - 120 )
        ? ( ret.top = position.y )
        : ( ret.bottom = height - position.y );
      return ret;
    },
    [ position ]
  );

  let text: string | null = null;
  if ( target ) {
    let currentTarget: HTMLElement | null = target as HTMLElement;
    while ( !text && currentTarget ) {
      text = currentTarget.dataset.stalker || null;
      currentTarget = currentTarget.parentElement;
    }
  }

  return <>
    { text && (
      <Root className={ className } style={ style }>
        { text }
      </Root>
    ) }
  </>;
};

export { Stalker };
